url: "https://voitiuk.com"
baseurl: ""

title: "Anna Voitiuk"
description: "Official website of Ukrainian printmaker and graphic artist Anna Voitiuk."
author: "Anna Voitiuk"
email: "anna.vojtiuk@gmail.com"
locale: "en"

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: base
      image: /assets/img/works/sightseeing-tour.jpg

formspree_form_path: "f/mykdekvr"

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - tmp
  - _legacy
