url: "https://voitiuk.com"
baseurl: ""

title: "Anna Voitiuk"
description: "Official website of Ukrainian printmaker and graphic artist Anna Voitiuk."
author: "Anna Voitiuk"
locale: "en"

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: base
      image: /assets/img/works/sightseeing-tour.jpg

formspree_form_id: "mykdekvr"
clarity_project_id: "y5fc1g7g0m"
etsy_shop_url: "https://voitiukprint.etsy.com"

include:
  - .well-known

exclude:
  - README.md
  - LICENSE
  - THIRD_PARTY_NOTICES.md
  - Gemfile
  - Gemfile.lock
  - tmp
  - _legacy
